### ISSUE TITLE
Streams without a preamble (newline) before the first boundary fail to parse

### ISSUE THREAD

**Issue by miunau** [Exact-Realty/ts-multipart-parser#1]
Hi,
Thanks for the parser, saved me a lot of time :)
I've noticed one thing- if the stream contains a boundary without a preamble before it, the parsing fails. This happens at least when passing Request body streams with multipart form data from Chrome. Once I add the newline in the beginning, it works.

See my test case here:
https://github.com/auth70/bodyguard/blob/main/tests/multipart.ts#L273 (request body from Chrome)

And the fix for that case:
https://github.com/auth70/bodyguard/blob/main/src/parser.ts#L172

Not sure where it should be fixed in your parser- I've gone over the code but the state machine assumes it's in preamble to begin with. Also I believe the spec requires a preamble which I suppose some browsers are just omitting. Maybe some kinda check if the character is a dash, or an option that can be passed in to just skip the preamble altogether?

**Comment by corrideat** [comment]
Hi @miunau 

Thanks for the report! I'm glad that the state machine implementation has been useful to you!

This is indeed an issue that didn't consider that the preamble could be completely empty, like in multi-part/form-data (well, an upcoming version will also handle the intricacies of form-data as well as the four different encodings allowed).

**Comment by corrideat** [comment]
This should be fixed now. Feel free to reopen if it still fails 😄

**Comment by miunau** [comment]
Thanks! Seems to be working fine.
