### ISSUE TITLE
Broken types on 1.0.10

### ISSUE THREAD

**Issue by miunau** [Exact-Realty/ts-multipart-parser#8]
Hi,
The package tries to import the cjs file even when using in esm mode:
https://arethetypeswrong.github.io/?p=%40exact-realty%2Fmultipart-parser%401.0.10

Some thoughts:
- default exports should be removed
- add `types` declaration to the package.json
- separate cjs and esm declaration files

I'm submitting a PR for this with 2.0.0 as the version as it'll break the default exports.

**Comment by corrideat** [comment]
Please see if the newly released version 1.0.11 fixes this. If it does, I'll close this.

**Comment by miunau** [comment]
Yep, thanks!
